apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest-deployment
  labels:
    app: guest-app
    type: guest-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: guest-app-pod
      app: demo-guest-app
  template:
    metadata:
      name: guest-app-pod
      labels:
        name: guest-app-pod
        app: demo-guest-app
    spec:
      containers:
        - name: guest-app
          image: kubernetes/guestbook:v2
          ports:
            - containerPort: 80