apiVersion: v1
kind: Service
metadata:
  name: guest-service
  labels:
    name: guest-service
    app: demo-guest-app
spec:
  type: NodePort
  selector: 
    name: guest-app-pod
    app: demo-guest-app
  ports:
  - port: 80
    targetPort: 80