apiVersion: v1
kind: Pod
metadata:
  name: guest-app-pod
  labels:
    name: guest-app-pod
    app: demo-guest-app
spec:
  containers:
  - name: guest-app
    image: kubernetes/guestbook:v2
    ports:
      - containerPort: 80